In [1]:
import numpy as np

In [2]:
x_dot_w = np.array([[0, 0, 0], [10, 10, 10]])
b  = np.array([1, 2, 3])

In [3]:
x_dot_w

array([[ 0,  0,  0],
       [10, 10, 10]])

In [4]:
x_dot_w+b

array([[ 1,  2,  3],
       [11, 12, 13]])

In [5]:
dy = np.array([[1, 2, 3], [4, 5, 6]])

In [6]:
dy

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
db = np.sum(dy, axis=0)

In [8]:
db

array([5, 7, 9])