In [1]:
import csv
import numpy as np

wine_path = '../data/csv/winequality-white.csv'
wineq_numpy = np.loadtxt(wine_path, dtype=np.float32, delimiter=';',skiprows=1)
wineq_numpy

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]], dtype=float32)

In [2]:
col_list = next(csv.reader(open(wine_path), delimiter=';'))

wineq_numpy.shape, col_list

((4898, 12),
 ['fixed acidity',
  'volatile acidity',
  'citric acid',
  'residual sugar',
  'chlorides',
  'free sulfur dioxide',
  'total sulfur dioxide',
  'density',
  'pH',
  'sulphates',
  'alcohol',
  'quality'])

In [3]:
import torch

wineq = torch.from_numpy(wineq_numpy)
wineq.shape, wineq.dtype

(torch.Size([4898, 12]), torch.float32)

In [4]:
data = wineq[:, :-1]
data, data.shape

(tensor([[ 7.0000,  0.2700,  0.3600,  ...,  3.0000,  0.4500,  8.8000],
         [ 6.3000,  0.3000,  0.3400,  ...,  3.3000,  0.4900,  9.5000],
         [ 8.1000,  0.2800,  0.4000,  ...,  3.2600,  0.4400, 10.1000],
         ...,
         [ 6.5000,  0.2400,  0.1900,  ...,  2.9900,  0.4600,  9.4000],
         [ 5.5000,  0.2900,  0.3000,  ...,  3.3400,  0.3800, 12.8000],
         [ 6.0000,  0.2100,  0.3800,  ...,  3.2600,  0.3200, 11.8000]]),
 torch.Size([4898, 11]))

In [7]:
# 정답 lable
target = wineq[:, -1].long()
target, target.dtype

(tensor([6, 6, 6,  ..., 6, 7, 6]), torch.int64)

### torch.Tensor.scatter_
Tensor.scatter_(dim, index, src, *, reduce=None) → Tensor

dim (int) – the axis along which to index

index (LongTensor) – the indices of elements to scatter, can be either empty or of the same dimensionality as src. When empty, the operation returns self unchanged.

value (Scalar) – the value to scatter.

In [12]:
# 원핫 인코딩 한 타겟 데이터
target_onehot = torch.zeros(target.shape[0], 10)

print(target_onehot.shape)

# target.unsqueeze(1) >> index는 LongTensor(int64)이여야함 >> batch size에서 batch size x 1 로
# 열로 흩뿌리는데, idex의 위치로 1.0을 target_onehot에 흩뿌려라.
target_onehot.scatter_(1, target.unsqueeze(1), 1.0)
print(target_onehot.shape)
target_onehot.dtype

torch.Size([4898, 10])
torch.Size([4898, 10])


torch.float32

In [10]:
target_unsqueezed = target.unsqueeze(1)
target_unsqueezed

tensor([[6],
        [6],
        [6],
        ...,
        [6],
        [7],
        [6]])

In [17]:
# 데이터의 각 행을 기준으로 평균을 구함(열이 11개이므로 개수가 11개)
data_mean = torch.mean(data, dim=0)
data_mean.shape

torch.Size([11])

In [ ]:
# 