### 연습문제

1. list(range(9))로 부터 텐서를 만들어보라. 사이즈, 오프셋, 스트라이드는 얼마일지 계산해 보라.   
**a**. b= a.view(3,3)으로 텐서를 만들어라. view의 역할은 무엇인가? a와 b가 같은 공간을 가리키고 있는지 확인해보라.   
**b**. c = b[1:,1:]로 텐서를 만들고 사이즈, 오프셋, 스트라이드는 얼마일지 계산해 보라.

In [1]:
import torch
# 사이즈는 크기가 9이니 9일꺼고, 오프셋은 시작점인데 0에서 시작할꺼고, 스트라이드는 1차원이니 (1,)
a = torch.tensor(list(range(9))) 
print(a)
print(a.size())
print(a.storage_offset())
print(a.stride())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
torch.Size([9])
0
(1,)


In [2]:
b = a.view(3,3)
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

### torch.Tensor.view
```Tensor.view(*shape) → Tensor```   
텐서와 같은 데이터 이지만 다른 shape의 텐서를 만든다. 데이터의 위치는 같다.
Returns a new tensor with the same data as the self tensor but of a different shape.

In [3]:
print(b.storage().data_ptr() == a.storage().data_ptr())
print(b.stride()) # (3,1)

True
(3, 1)


/tmp/ipykernel_83032/3932823291.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  print(b.storage().data_ptr() == a.storage().data_ptr())


In [4]:
# b = 3 x 3, c = 2 x 2 
c = b[1:,1:]
# c의 사이즈는 2x2이고, offset은 4부터 시작하니 4일꺼고, 
# 스트라이드는 열은 1씩 증가하니깐 1이고 행은 3씩 증가히니깐 (3,1)
print(c)
print(c.size())
print(c.storage_offset())
print(c.stride())

tensor([[4, 5],
        [7, 8]])
torch.Size([2, 2])
4
(3, 1)


2. 코사인이나 제곱근 같은 수학 연산을 하나 골라라. 동일한 역할을 하는 함수를 torch라이브러리에서 찾을 수 있을까?   
**a**. 텐서 a에 대해 해당함수를 요소 단위로 실행해보라. 왜 오류가 발생할까?   
**b**. 동작시키려면 어떤 연산이 필요할까?   
**c**. 해당 연산을 추가 공간을 사용하지 않고 실행하는 함수가 있을까?   


### torch.cos
torch.cos(input, *, out=None) → Tensor
Returns a new tensor with the cosine of the elements of input.


In [5]:
torch.cos(a[0])

tensor(1.)

In [6]:
torch.cos(a) # ??? 

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])

### 여기는 챗지피티한테 물어본 해답

In [7]:
# Tensor 생성
a = torch.tensor([1, 2, 3], dtype=torch.int32)

cosine_fn = torch.cos

In [8]:
a

tensor([1, 2, 3], dtype=torch.int32)

In [9]:
# 코사인 함수 적용
try:
    result = cosine_fn(a)
except RuntimeError as e:
    print("Error:", e)

In [10]:
# In-place 연산 실행
try:
    a.cos_()
except RuntimeError as e:
    print("Error with in-place operation:", e)

Error with in-place operation: result type Float can't be cast to the desired output type Int


In [12]:
# cos_()는 새로운 텐서를 생성하지 않고 데이터를 넣어 사용, 근데 torch.cos()함수는 부동 소수점일때만, 작동
# cos() 함수는 부동소수점이 아닐경우 자동으로 부동 소수점으로 바꿔주는듯.
a_result = a.float().cos_()
a_result

tensor([ 0.5403, -0.4161, -0.9900])