In [26]:
import torch

a = torch.ones(3) # 크기가 3인 1차원 텐서를 만들고 1로 채우기
a

tensor([1., 1., 1.])

In [27]:
float(a[1])

1.0

In [28]:
a[2] = 2.0
a[2]

tensor(2.)

### 89p
### 텐서나 넘파이 배열은 파이썬 객체가 아닌 언박싱된 C언어의 숫자 타입을 포함한 연속적인 메모리가 할당되고 이에 대한 뷰를 제공한다. >> c언어의 숫자 타입을 사용한다는 뜻.

In [29]:
# 각 요소는 32비트(4바이트)float타입이다. 
print(a.dtype)
print(a[1].dtype)

torch.float32
torch.float32


In [30]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0]) # 리스트도 당연히 인자로 됨
points

tensor([4., 1., 5., 3., 2., 1.])

In [31]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [32]:
list = [1,2,3,4] # 소괄호가 되는게 신기해서 list도 되나 확인함
list[0],list[1],list[2]

(1, 2, 3)

In [33]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
print(points.shape)
print(points)

torch.Size([3, 2])
tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])


In [34]:
points[0]

tensor([4., 1.])

### 이미지 데이터를 흑백으로 변환

In [35]:
img_1 = torch.randn(3, 5, 5)  # [채널, 행, 열]
img_2 = torch.randn(5, 5, 3)  # [행, 열, 채널]

# RGB 채널 참조
print(img_1[-3].shape)  # (5, 5), 채널이 첫 번째 차원
print(img_2[-3].shape)  # (5, 5), 채널이 마지막 차원

torch.Size([5, 5])
torch.Size([5, 3])


In [36]:
print(img_1)  # (5, 5), 채널이 첫 번째 차원

tensor([[[ 0.4191,  2.0126,  0.6983, -2.0143,  2.1529],
         [ 0.0378,  1.8441,  0.3956, -1.7088,  1.2046],
         [-1.5089,  0.0125, -1.5309, -0.7492, -1.8526],
         [-0.5963,  0.6359, -0.2701, -1.8439,  0.2477],
         [-0.8653, -2.1381, -1.7105, -1.9565,  1.1573]],

        [[ 0.0901, -0.6128, -1.5453, -0.3724,  0.9097],
         [-0.8483, -0.4179, -1.4720, -0.7114,  1.6299],
         [ 2.0467, -2.9343,  0.7537, -0.0783,  1.7529],
         [-0.5254,  0.2190,  1.1582, -0.3140,  1.8583],
         [-0.8087, -1.1784, -1.4031,  1.1891,  0.4616]],

        [[ 0.8568,  1.2256, -0.9270, -0.2133, -0.2199],
         [ 0.1268, -0.5539,  1.6500,  1.0087, -2.6191],
         [ 0.9202, -0.2447, -1.1638, -0.3775, -0.1074],
         [ 0.8161,  1.4235,  2.3678, -0.3060,  0.1983],
         [ 1.0594, -0.0482,  0.2501,  0.4283, -1.0515]]])


In [37]:
print(img_1[-3])

tensor([[ 0.4191,  2.0126,  0.6983, -2.0143,  2.1529],
        [ 0.0378,  1.8441,  0.3956, -1.7088,  1.2046],
        [-1.5089,  0.0125, -1.5309, -0.7492, -1.8526],
        [-0.5963,  0.6359, -0.2701, -1.8439,  0.2477],
        [-0.8653, -2.1381, -1.7105, -1.9565,  1.1573]])


### 93p 
### RGB채널은 0번 혹은 1번 차원에 있다.두 경우 모두 뒤에서 부터 세 번째 차원이므로 RGB 채널은 -3번 차원에 있는 것으로 일반화 할 수 있다. << 가장 뒤에 2개는 행, 열일테니 -3번째는 당연히 RGB값이 나온 층

In [38]:
img_t = torch.randn(3, 5, 5) # [채널 크기, 행 크기, 열 크기]
weights = torch.tensor([0.2126, 0.7152, 0.0722])

batch_t = torch.randn(2, 3, 5, 5) # 배치 크기 2, [채널 크기, 행 크기, 열 크기]

In [39]:
img_gray_naive = img_t.mean(-3) # -1, -2, -3 층 의  평균
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [40]:
img_gray_naive

tensor([[ 0.7886,  0.2605, -0.1324, -1.3133,  0.1325],
        [-0.3529, -1.3788,  0.8662, -0.2418,  1.0876],
        [ 1.3358, -0.2636, -0.8288,  0.7054,  0.6459],
        [-0.2129, -0.9313,  0.6914, -0.2465,  0.6578],
        [ 0.8677, -0.8764, -0.2207,  0.6798,  0.6121]])

In [41]:
print(img_t[0, 0, 0], img_t[1, 0, 0], img_t[2, 0, 0])
print((float(img_t[0, 0, 0])+ float(img_t[1, 0, 0])+ float(img_t[2, 0, 0]))/3.0)

tensor(2.4769) tensor(1.3710) tensor(-1.4821)
0.7885956764221191


**squeeze** 함수는 Tensor의 차원을 줄이는 함수로, 설정한 차원을 제거 해 준다.

따로 차원을 설정하지 않으면 1인 차원을 모두 제거한다. 1인 차원이 여러개 있어도 여러개를 전부 제거한다.

반대로 **unsqueeze** 함수는 squeeze 함수와 반대로 차원을 늘려주는 함수인데, 1인 차원을 생성한다. unsqueeze 함수를 사용할 땐 어느 차원에 1인 차원을 생성을 할 것인지를 지정 해 주어야만 한다.

In [42]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)
print(unsqueezed_weights)
print(unsqueezed_weights.shape)

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])
torch.Size([3, 1, 1])


In [43]:
# 3x5x5 와 3x1x1를 곱함 << 브로드캐스팅 (크기가 같거나, 한쪽이 1이거나)
img_weights = (img_t * unsqueezed_weights)
# 2x3x5x5 와 3x1x1를 곱함
batch_weights = (batch_t * unsqueezed_weights)
# 3x5x5<<5x5가 3개, 이를 더한다>> 5x5차원 하나로 나옴
img_gray_weighted = img_weights.sum(-3)
# 2x3x5x5<< 3x5x5가 2개, 이를 -3차원 기준으로 더한다 >> 5x5차원의 값이 2개로 나옴 2x5x5
batch_gray_weighted = batch_weights.sum(-3)
print('batch weight      : ', batch_weights.shape,
      '\nbatch gray weight : ',batch_gray_weighted.shape,
      '\nimg weights       : ', img_weights.shape,
      '\nimg gray weights  : ',img_gray_weighted.shape)

batch weight      :  torch.Size([2, 3, 5, 5]) 
batch gray weight :  torch.Size([2, 5, 5]) 
img weights       :  torch.Size([3, 5, 5]) 
img gray weights  :  torch.Size([5, 5])


In [44]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

### 텐서의 이름 붙이기 아직은 실험적인 기능

In [45]:
# refine_names << 이미 만들고 나중에 이름을 붙일때, 쓰는 함수
img_named =  img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [46]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [47]:
# 이름 설정시 자기가 알아서 차원을 알맞게 맞춰 준다.
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [48]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [49]:
# 이름이 다른 차원을 결합하면, 에러
gray_named = (img_named[..., :3] * weights_named).sum('channels')

RuntimeError: Error when attempting to broadcast dims ['channels', 'rows', 'columns'] and dims ['channels']: dim 'columns' and dim 'channels' are at the same position from the right but do not match.

In [36]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))